// ACHIEVEMENTS
export const ADD_ACHIEVEMENT_SUCCESS = "ADD_ACHIEVEMENT_SUCCESS";
export const DELETE_ACHIEVEMENT_SUCCESS = "DELETE_ACHIEVEMENT_SUCCESS";
export const EDIT_ACHIEVEMENT_SUCCESS = "EDIT_ACHIEVEMENT_SUCCESS";
export const FETCH_ACHIEVEMENTS_SUCCESS = "FETCH_ACHIEVEMENTS_SUCCESS";


// ACHIEVEMENT TYPES
export const ADD_ACHIEVEMENT_TYPE_SUCCESS = "ADD_ACHIEVEMENT_TYPE_SUCCESS";
export const DELETE_ACHIEVEMENT_TYPE_SUCCESS = "DELETE_ACHIEVEMENT_TYPE_SUCCESS";
export const EDIT_ACHIEVEMENT_TYPE_SUCCESS = "EDIT_ACHIEVEMENT_TYPE_SUCCESS";
export const FETCH_ACHIEVEMENT_TYPES_SUCCESS = "FETCH_ACHIEVEMENT_TYPES_SUCCESS";


// ATHLETES
export const ADD_ATHLETE_SUCCESS = "ADD_ATHLETE_SUCCESS";
export const DELETE_ATHLETE_SUCCESS = "DELETE_ATHLETE_SUCCESS";
export const EDIT_ATHLETE_SUCCESS = "EDIT_ATHLETE_SUCCESS";
export const FETCH_ATHLETES_SUCCESS = "FETCH_ATHLETES_SUCCESS";


// COMPETITIONS
export const ADD_COMPETITION_SUCCESS = "ADD_COMPETITION_SUCCESS";
export const DELETE_COMPETITION_SUCCESS = "DELETE_COMPETITION_SUCCESS";
export const EDIT_COMPETITION_SUCCESS = "EDIT_COMPETITION_SUCCESS";
export const FETCH_COMPETITIONS_SUCCESS = "FETCH_COMPETITIONS_SUCCESS";


// COMPETITION TYPES
export const ADD_COMPETITION_TYPE_SUCCESS = "ADD_COMPETITION_TYPE_SUCCESS";
export const DELETE_COMPETITION_TYPE_SUCCESS = "DELETE_COMPETITION_TYPE_SUCCESS";
export const EDIT_COMPETITION_TYPE_SUCCESS = "EDIT_COMPETITION_TYPE_SUCCESS";
export const FETCH_COMPETITION_TYPES_SUCCESS = "FETCH_COMPETITION_TYPES_SUCCESS";


// COUNTRIES
export const ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS";
export const DELETE_COUNTRY_SUCCESS = "DELETE_COUNTRY_SUCCESS";
export const EDIT_COUNTRY_SUCCESS = "EDIT_COUNTRY_SUCCESS";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";


// EVENTS
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_BY_SPORT_SUCCESS = "FETCH_EVENTS_BY_SPORT_SUCCESS";


// SPORTS
export const ADD_SPORT_SUCCESS = "ADD_SPORT_SUCCESS";
export const DELETE_SPORT_SUCCESS = "DELETE_SPORT_SUCCESS";
export const EDIT_SPORT_SUCCESS = "EDIT_SPORT_SUCCESS";
export const FETCH_SPORTS_SUCCESS = "FETCH_SPORTS_SUCCESS";


// UI
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const HIDE_LOADING = "HIDE_LOADING";
export const SHOW_LOADING = "SHOW_LOADING";
export const SHOW_ERROR = "SHOW_ERROR";
export const SHOW_SUCCESS = "SHOW_SUCCESS";